#!/usr/bin/env bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
script_name=$(basename $0)
config_file=$script_dir/config

source $config_file

now=`date +"%Y%m%d-%H%M%S"`

# Check permissions on this file.
perms=$(stat $script_dir/config | sed -n '/^Access: (/{s/Access: (\([0-9]\+\).*$/\1/;p}')
if [[ "$perms" != "0700" ]]; then
    echo "WARNING: It is recommended to set '$config_file' permissions to '0600.'"
fi

# Check for tt-rss update cron job.
echo "Checking cron jobs."
if ! crontab -l | grep -q "$script_name"; then
    # Add tt-rss update cron job.
    echo "Adding tt-rss update cron job."
    crontab -l | { cat; echo "0 3 1 * *	$script_dir/$script_name"; } | crontab -
fi

# Check for feed update cron job.
if ! crontab -l | grep -q "/update.php --feeds"; then
    # Add feed update cron job.
    echo "Adding feed update cron job."
    crontab -l | { cat; echo "*/5 * * * *	/usr/bin/php $dir_tt/update.php --feeds --quiet &> /dev/null"; } | crontab -
fi

# Stop feed update cron job.
echo "Stopping feed update."
crontab -l | sed -e "/update.php --feeds/ s/^#*/#/" | crontab -

# Backup current install, delete backups older than 60 days.
if [ -d $dir_tt ]; then
    cd "$( dirname "$dir_tt" )"
    mkdir -p $dir_bk
    echo "Backing up tt-rss directory."
    tar -cf $dir_bk/tt-rss-${now}.tar -C $(dirname $dir_tt) $(basename $dir_tt)
    echo "Backing up tt-rss database."
    if [ "$DB_TYPE" == "mysql" ]; then
        mysqldump -h$DB_HOST -u$DB_USER -p$DB_PASS $DB_NAME 2>/dev/null | bzip2 > $dir_bk/tt-rss-db-${now}.sql.bz2
    elif [ "$DB_TYPE" == "pgsql" ]; then
        # This may not work since I haven't tested it with postgresql,
        # you probably need a .pgpass file in your home directory at the
        # least with your password in it.
        pg_dump -h$DB_HOST -U$DB_USER $DB_NAME 2>/dev/null | bzip2 > $dir_bk/tt-rss-db-${now}.sql.bz2
    fi
    find $dir_bk -mtime +60 -exec rm {} \;
fi

# Pull from git.
if [ ! -d $dir_tt/.git ]; then
    echo "Cloning from git repository."
    git clone https://git.tt-rss.org/git/tt-rss $dir_tt
else
    echo "Pulling from git repository."
    cd $dir_tt
    git pull
fi

# Always use new config file, there maybe new parameters.
echo "Updating config.php."
cp $dir_tt/config.php-dist $dir_tt/config.php

# Change config file to personalized settings.
sed -i "/DB_TYPE/ s/%DB_TYPE/$DB_TYPE/" $dir_tt/config.php
sed -i "/DB_HOST/ s/%DB_HOST/$DB_HOST/" $dir_tt/config.php
sed -i "/DB_NAME/ s/%DB_NAME/$DB_NAME/" $dir_tt/config.php
sed -i "/DB_USER/ s/%DB_USER/$DB_USER/" $dir_tt/config.php
sed -i "/DB_PASS/ s/%DB_PASS/$DB_PASS/" $dir_tt/config.php
sed -i "/DB_PORT/ s/%DB_PORT/$DB_PORT/" $dir_tt/config.php
sed -i "/SELF_URL_PATH/ s,%SELF_URL_PATH,$SELF_URL_PATH," $dir_tt/config.php

# Restrict permissions on config file.
chmod 0700 $dir_tt/config.php

# Update .htaccess file.
echo "Updating .htaccess file."
cat << EOF > $dir_tt/.htaccess
<FilesMatch "^\.">
    Require all denied
</FilesMatch>

<IfModule alias_module>
    RedirectMatch 404 /config.php
    RedirectMatch 404 /README.md
    RedirectMatch 404 /\.git
    RedirectMatch 404 /cache
</IfModule>
EOF

# Start feed update cron job.
echo "Starting feed update."
crontab -l | sed -e "/update.php --feeds/ s/#*//" | crontab -

# Check website for errors.
if [[ $(curl -s -I -o /dev/null -w '%{http_code}' $SELF_URL_PATH) != 200 ]] || curl -s $SELF_URL_PATH | grep -q "Startup failed"; then
    echo "Error loading webpage."
else
    echo "No webpage errors detected."
fi
